# ASP.NET Core
# Build a Web project that uses ASP.NET Core.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# YAML reference:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - src/PureCloud.Utils.Function.Recording/*
    - src/PureCloud.Utils.Function.User/*
    - README.md

resources:
- repo: self

jobs:
- template: /templates/function-build.yml
  parameters:
    name: Conversation.Function
    vmImage: 'Ubuntu-16.04'
    buildprojects: '**/*.Function.Conversation.csproj'
    buildConfiguration: 'Release'
    artifactstagingdirectory: $(build.artifactstagingdirectory)
    artifactName: 'conversation'
